name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build the project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Check environment variables
        run: |
          echo "DB_HOST is set? ${DB_HOST:+YES}"
          echo "DB_PORT is set? ${DB_PORT:+YES}"
          echo "DB_USERNAME is set? ${DB_USERNAME:+YES}"
          echo "DB_NAME is set? ${DB_NAME:+YES}"
          echo "REFRESH_TOKEN_SECRET is set? ${REFRESH_TOKEN_SECRET:+YES}"
          echo "JWKS_URI is set? ${JWKS_URI:+YES}"

      - name: Test DB connection
        run: |
          echo "Testing Postgres connection..."
          # Only log the host and port, not the password
          echo "Connecting to $DB_HOST:$DB_PORT as $DB_USERNAME"
          # Test connectivity without revealing sensitive info
          pg_isready -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USERNAME"

      - name: Test and coverage
        run: npm run test
        env:
          DB_HOST: ${{ secrets.TEST_DB_HOST }}
          DB_PORT: ${{ secrets.TEST_DB_PORT }}
          DB_USERNAME: ${{ secrets.TEST_DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
          DB_NAME: ${{ secrets.TEST_DB_NAME }}
          REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
          JWKS_URI: ${{ secrets.JWKS_URI }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

      - name: Build-ts
        run: npm run build

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-and-push-docker:
    name: Build and Push Docker Image
    needs: build-and-test
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: saudjavaidakram/mernstack_auth_service
      IMAGE_TAG: build-${{ github.run_number }}
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} --platform linux/amd64 -f docker/prod/Dockerfile .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
