name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build the project
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test_user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: test_user
      DB_PASSWORD: test_password
      DB_NAME: test_db
      REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
      JWKS_URI: ${{ secrets.JWKS_URI }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Check environment variables
        run: |
          echo "DB_HOST is set? ${DB_HOST:+YES}"
          echo "DB_PORT is set? ${DB_PORT:+YES}"
          echo "DB_USERNAME is set? ${DB_USERNAME:+YES}"
          echo "REFRESH_TOKEN_SECRET is set? ${REFRESH_TOKEN_SECRET:+YES}"
          echo "JWKS_URI is set? ${JWKS_URI:+YES}"

      - name: Test Postgres connection
        run: |
          echo "Testing Postgres connection..."
          PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -U $DB_USERNAME -d $DB_NAME -c "\l"

      - name: Test and coverage
        run: npm run test

      - name: Build-ts
        run: npm run build

      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-and-push-docker:
    name: Build and Push Docker Image
    needs: build-and-test
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: saudjavaidakram/mernstack_auth_service
      IMAGE_TAG: build-${{ github.run_number }}
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} --platform linux/amd64 -f docker/prod/Dockerfile .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
